// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf.proto

/*
Package trustedentity is a generated protocol buffer package.

It is generated from these files:
	protobuf.proto

It has these top-level messages:
	MyReqRequest
	MyReqReply
	SecretRequest
	SecretReply
	CACertificateRequest
	CACertificateReply
	CurrentCRLRequest
	CurrentCRLReply
	CreateCACertificateRequest
	CreateCACertificateReply
*/
package trustedentity

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MyReqRequest struct {
}

func (m *MyReqRequest) Reset()                    { *m = MyReqRequest{} }
func (m *MyReqRequest) String() string            { return proto.CompactTextString(m) }
func (*MyReqRequest) ProtoMessage()               {}
func (*MyReqRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type MyReqReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *MyReqReply) Reset()                    { *m = MyReqReply{} }
func (m *MyReqReply) String() string            { return proto.CompactTextString(m) }
func (*MyReqReply) ProtoMessage()               {}
func (*MyReqReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MyReqReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// The request message containing the secret name.
type SecretRequest struct {
	SecretPath string `protobuf:"bytes,1,opt,name=secretPath" json:"secretPath,omitempty"`
}

func (m *SecretRequest) Reset()                    { *m = SecretRequest{} }
func (m *SecretRequest) String() string            { return proto.CompactTextString(m) }
func (*SecretRequest) ProtoMessage()               {}
func (*SecretRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SecretRequest) GetSecretPath() string {
	if m != nil {
		return m.SecretPath
	}
	return ""
}

// The response message containing the secret
type SecretReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *SecretReply) Reset()                    { *m = SecretReply{} }
func (m *SecretReply) String() string            { return proto.CompactTextString(m) }
func (*SecretReply) ProtoMessage()               {}
func (*SecretReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SecretReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// The request message for the CACertificate.
type CACertificateRequest struct {
}

func (m *CACertificateRequest) Reset()                    { *m = CACertificateRequest{} }
func (m *CACertificateRequest) String() string            { return proto.CompactTextString(m) }
func (*CACertificateRequest) ProtoMessage()               {}
func (*CACertificateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

// The response message containing the CACertificate
type CACertificateReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *CACertificateReply) Reset()                    { *m = CACertificateReply{} }
func (m *CACertificateReply) String() string            { return proto.CompactTextString(m) }
func (*CACertificateReply) ProtoMessage()               {}
func (*CACertificateReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CACertificateReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// The request message for the CRL request.
type CurrentCRLRequest struct {
}

func (m *CurrentCRLRequest) Reset()                    { *m = CurrentCRLRequest{} }
func (m *CurrentCRLRequest) String() string            { return proto.CompactTextString(m) }
func (*CurrentCRLRequest) ProtoMessage()               {}
func (*CurrentCRLRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

// The response message containing the CRL response
type CurrentCRLReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *CurrentCRLReply) Reset()                    { *m = CurrentCRLReply{} }
func (m *CurrentCRLReply) String() string            { return proto.CompactTextString(m) }
func (*CurrentCRLReply) ProtoMessage()               {}
func (*CurrentCRLReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CurrentCRLReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// The request message for the CreateCACertificate request.
type CreateCACertificateRequest struct {
	Role       string `protobuf:"bytes,1,opt,name=role" json:"role,omitempty"`
	CommonName string `protobuf:"bytes,2,opt,name=commonName" json:"commonName,omitempty"`
	Ttl        string `protobuf:"bytes,3,opt,name=ttl" json:"ttl,omitempty"`
}

func (m *CreateCACertificateRequest) Reset()                    { *m = CreateCACertificateRequest{} }
func (m *CreateCACertificateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateCACertificateRequest) ProtoMessage()               {}
func (*CreateCACertificateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CreateCACertificateRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *CreateCACertificateRequest) GetCommonName() string {
	if m != nil {
		return m.CommonName
	}
	return ""
}

func (m *CreateCACertificateRequest) GetTtl() string {
	if m != nil {
		return m.Ttl
	}
	return ""
}

// The response message containing the CreateCACertificate response
type CreateCACertificateReply struct {
	Certificate    string `protobuf:"bytes,1,opt,name=certificate" json:"certificate,omitempty"`
	IssuingCa      string `protobuf:"bytes,2,opt,name=issuing_ca,json=issuingCa" json:"issuing_ca,omitempty"`
	PrivateKey     string `protobuf:"bytes,3,opt,name=private_key,json=privateKey" json:"private_key,omitempty"`
	PrivateKeyType string `protobuf:"bytes,4,opt,name=private_key_type,json=privateKeyType" json:"private_key_type,omitempty"`
	SerialNumber   string `protobuf:"bytes,5,opt,name=serial_number,json=serialNumber" json:"serial_number,omitempty"`
}

func (m *CreateCACertificateReply) Reset()                    { *m = CreateCACertificateReply{} }
func (m *CreateCACertificateReply) String() string            { return proto.CompactTextString(m) }
func (*CreateCACertificateReply) ProtoMessage()               {}
func (*CreateCACertificateReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *CreateCACertificateReply) GetCertificate() string {
	if m != nil {
		return m.Certificate
	}
	return ""
}

func (m *CreateCACertificateReply) GetIssuingCa() string {
	if m != nil {
		return m.IssuingCa
	}
	return ""
}

func (m *CreateCACertificateReply) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

func (m *CreateCACertificateReply) GetPrivateKeyType() string {
	if m != nil {
		return m.PrivateKeyType
	}
	return ""
}

func (m *CreateCACertificateReply) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func init() {
	proto.RegisterType((*MyReqRequest)(nil), "trustedentity.MyReqRequest")
	proto.RegisterType((*MyReqReply)(nil), "trustedentity.MyReqReply")
	proto.RegisterType((*SecretRequest)(nil), "trustedentity.SecretRequest")
	proto.RegisterType((*SecretReply)(nil), "trustedentity.SecretReply")
	proto.RegisterType((*CACertificateRequest)(nil), "trustedentity.CACertificateRequest")
	proto.RegisterType((*CACertificateReply)(nil), "trustedentity.CACertificateReply")
	proto.RegisterType((*CurrentCRLRequest)(nil), "trustedentity.CurrentCRLRequest")
	proto.RegisterType((*CurrentCRLReply)(nil), "trustedentity.CurrentCRLReply")
	proto.RegisterType((*CreateCACertificateRequest)(nil), "trustedentity.CreateCACertificateRequest")
	proto.RegisterType((*CreateCACertificateReply)(nil), "trustedentity.CreateCACertificateReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SecretKeeper service

type SecretKeeperClient interface {
	// Sends a test request
	SayMyReq(ctx context.Context, in *MyReqRequest, opts ...grpc.CallOption) (*MyReqReply, error)
	// Sends a request for a secret
	SaySecret(ctx context.Context, in *SecretRequest, opts ...grpc.CallOption) (*SecretReply, error)
	// Sends a request for retrieving a CACertificate
	SayCACertificate(ctx context.Context, in *CACertificateRequest, opts ...grpc.CallOption) (*CACertificateReply, error)
	// Sends a request for current CRL in raw DER-encoded form
	SayCurrentCRL(ctx context.Context, in *CurrentCRLRequest, opts ...grpc.CallOption) (*CurrentCRLReply, error)
	// Sends a request for creating a CACertificate
	SayCreateCACertificate(ctx context.Context, in *CreateCACertificateRequest, opts ...grpc.CallOption) (*CreateCACertificateReply, error)
}

type secretKeeperClient struct {
	cc *grpc.ClientConn
}

func NewSecretKeeperClient(cc *grpc.ClientConn) SecretKeeperClient {
	return &secretKeeperClient{cc}
}

func (c *secretKeeperClient) SayMyReq(ctx context.Context, in *MyReqRequest, opts ...grpc.CallOption) (*MyReqReply, error) {
	out := new(MyReqReply)
	err := grpc.Invoke(ctx, "/trustedentity.SecretKeeper/SayMyReq", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretKeeperClient) SaySecret(ctx context.Context, in *SecretRequest, opts ...grpc.CallOption) (*SecretReply, error) {
	out := new(SecretReply)
	err := grpc.Invoke(ctx, "/trustedentity.SecretKeeper/SaySecret", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretKeeperClient) SayCACertificate(ctx context.Context, in *CACertificateRequest, opts ...grpc.CallOption) (*CACertificateReply, error) {
	out := new(CACertificateReply)
	err := grpc.Invoke(ctx, "/trustedentity.SecretKeeper/SayCACertificate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretKeeperClient) SayCurrentCRL(ctx context.Context, in *CurrentCRLRequest, opts ...grpc.CallOption) (*CurrentCRLReply, error) {
	out := new(CurrentCRLReply)
	err := grpc.Invoke(ctx, "/trustedentity.SecretKeeper/SayCurrentCRL", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretKeeperClient) SayCreateCACertificate(ctx context.Context, in *CreateCACertificateRequest, opts ...grpc.CallOption) (*CreateCACertificateReply, error) {
	out := new(CreateCACertificateReply)
	err := grpc.Invoke(ctx, "/trustedentity.SecretKeeper/SayCreateCACertificate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SecretKeeper service

type SecretKeeperServer interface {
	// Sends a test request
	SayMyReq(context.Context, *MyReqRequest) (*MyReqReply, error)
	// Sends a request for a secret
	SaySecret(context.Context, *SecretRequest) (*SecretReply, error)
	// Sends a request for retrieving a CACertificate
	SayCACertificate(context.Context, *CACertificateRequest) (*CACertificateReply, error)
	// Sends a request for current CRL in raw DER-encoded form
	SayCurrentCRL(context.Context, *CurrentCRLRequest) (*CurrentCRLReply, error)
	// Sends a request for creating a CACertificate
	SayCreateCACertificate(context.Context, *CreateCACertificateRequest) (*CreateCACertificateReply, error)
}

func RegisterSecretKeeperServer(s *grpc.Server, srv SecretKeeperServer) {
	s.RegisterService(&_SecretKeeper_serviceDesc, srv)
}

func _SecretKeeper_SayMyReq_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MyReqRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretKeeperServer).SayMyReq(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trustedentity.SecretKeeper/SayMyReq",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretKeeperServer).SayMyReq(ctx, req.(*MyReqRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretKeeper_SaySecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretKeeperServer).SaySecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trustedentity.SecretKeeper/SaySecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretKeeperServer).SaySecret(ctx, req.(*SecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretKeeper_SayCACertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CACertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretKeeperServer).SayCACertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trustedentity.SecretKeeper/SayCACertificate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretKeeperServer).SayCACertificate(ctx, req.(*CACertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretKeeper_SayCurrentCRL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurrentCRLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretKeeperServer).SayCurrentCRL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trustedentity.SecretKeeper/SayCurrentCRL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretKeeperServer).SayCurrentCRL(ctx, req.(*CurrentCRLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretKeeper_SayCreateCACertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCACertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretKeeperServer).SayCreateCACertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trustedentity.SecretKeeper/SayCreateCACertificate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretKeeperServer).SayCreateCACertificate(ctx, req.(*CreateCACertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SecretKeeper_serviceDesc = grpc.ServiceDesc{
	ServiceName: "trustedentity.SecretKeeper",
	HandlerType: (*SecretKeeperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayMyReq",
			Handler:    _SecretKeeper_SayMyReq_Handler,
		},
		{
			MethodName: "SaySecret",
			Handler:    _SecretKeeper_SaySecret_Handler,
		},
		{
			MethodName: "SayCACertificate",
			Handler:    _SecretKeeper_SayCACertificate_Handler,
		},
		{
			MethodName: "SayCurrentCRL",
			Handler:    _SecretKeeper_SayCurrentCRL_Handler,
		},
		{
			MethodName: "SayCreateCACertificate",
			Handler:    _SecretKeeper_SayCreateCACertificate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf.proto",
}

func init() { proto.RegisterFile("protobuf.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 468 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdb, 0x6e, 0xd3, 0x40,
	0x10, 0x25, 0xa4, 0x5c, 0x32, 0xb9, 0x90, 0x0e, 0xa8, 0x32, 0x06, 0x42, 0x70, 0x25, 0x5a, 0x84,
	0x64, 0x24, 0x10, 0x1f, 0x40, 0x8d, 0xc4, 0x43, 0xa1, 0x8a, 0x62, 0x1e, 0x91, 0xa2, 0x8d, 0x99,
	0x06, 0x0b, 0x5f, 0xb6, 0xbb, 0x6b, 0xc4, 0xfe, 0x1d, 0xef, 0xfc, 0x14, 0xf2, 0x7a, 0x4d, 0x1c,
	0x93, 0x5a, 0xbc, 0xed, 0x9e, 0x3d, 0xe7, 0xcc, 0x68, 0xe6, 0x68, 0x61, 0xc2, 0x45, 0xae, 0xf2,
	0x75, 0x71, 0xe9, 0x9b, 0x03, 0x8e, 0x95, 0x28, 0xa4, 0xa2, 0xaf, 0x94, 0xa9, 0x58, 0x69, 0x6f,
	0x02, 0xa3, 0x4f, 0x7a, 0x49, 0x57, 0x4b, 0xba, 0x2a, 0x48, 0x2a, 0xef, 0x39, 0x80, 0xbd, 0xf3,
	0x44, 0xa3, 0x03, 0x77, 0x52, 0x92, 0x92, 0x6d, 0xc8, 0xe9, 0xcd, 0x7b, 0xa7, 0x83, 0x65, 0x7d,
	0xf5, 0x5e, 0xc1, 0x38, 0xa4, 0x48, 0x90, 0xb2, 0x42, 0x9c, 0x01, 0x48, 0x03, 0x2c, 0x98, 0xfa,
	0x66, 0xd9, 0x0d, 0xc4, 0x3b, 0x81, 0x61, 0x2d, 0xe8, 0x76, 0x3e, 0x82, 0x07, 0xc1, 0xbb, 0x80,
	0x84, 0x8a, 0x2f, 0xe3, 0x88, 0x29, 0xaa, 0x3b, 0xf3, 0x01, 0x5b, 0x78, 0xb7, 0xcf, 0x7d, 0x38,
	0x0c, 0x0a, 0x21, 0x28, 0x53, 0xc1, 0xf2, 0x63, 0x6d, 0xf2, 0x12, 0xee, 0x35, 0xc1, 0x6e, 0x87,
	0x35, 0xb8, 0x81, 0x20, 0xa6, 0x68, 0x5f, 0x3f, 0x88, 0x70, 0x20, 0xf2, 0xa4, 0x16, 0x99, 0x73,
	0x39, 0x84, 0x28, 0x4f, 0xd3, 0x3c, 0xbb, 0x60, 0x29, 0x39, 0x37, 0xab, 0x21, 0x6c, 0x11, 0x9c,
	0x42, 0x5f, 0xa9, 0xc4, 0xe9, 0x9b, 0x87, 0xf2, 0xe8, 0xfd, 0xee, 0x81, 0xb3, 0xb7, 0x48, 0xd9,
	0xda, 0x1c, 0x86, 0xd1, 0x16, 0xb3, 0x95, 0x9a, 0x10, 0x3e, 0x01, 0x88, 0xa5, 0x2c, 0xe2, 0x6c,
	0xb3, 0x8a, 0x98, 0x2d, 0x38, 0xb0, 0x48, 0xc0, 0xf0, 0x29, 0x0c, 0xb9, 0x88, 0x7f, 0x30, 0x45,
	0xab, 0xef, 0xa4, 0x6d, 0x5d, 0xb0, 0xd0, 0x39, 0x69, 0x3c, 0x85, 0x69, 0x83, 0xb0, 0x52, 0x9a,
	0x93, 0x73, 0x60, 0x58, 0x93, 0x2d, 0xeb, 0xb3, 0xe6, 0x84, 0xc7, 0x30, 0x96, 0x24, 0x62, 0x96,
	0xac, 0xb2, 0x22, 0x5d, 0x93, 0x70, 0x6e, 0x19, 0xda, 0xa8, 0x02, 0x2f, 0x0c, 0xf6, 0xfa, 0x57,
	0x1f, 0x46, 0xd5, 0x96, 0xcf, 0x89, 0x38, 0x09, 0x7c, 0x0f, 0x77, 0x43, 0xa6, 0x4d, 0xa2, 0xf0,
	0x91, 0xbf, 0x13, 0x3d, 0xbf, 0x99, 0x3b, 0xf7, 0xe1, 0xfe, 0x47, 0x9e, 0x68, 0xef, 0x06, 0x7e,
	0x80, 0x41, 0xc8, 0x74, 0x65, 0x8c, 0x8f, 0x5b, 0xcc, 0x9d, 0x18, 0xba, 0xee, 0x35, 0xaf, 0x95,
	0xd1, 0x17, 0x98, 0x86, 0x4c, 0xef, 0x4c, 0x1a, 0x8f, 0x5b, 0x8a, 0x7d, 0xcb, 0x76, 0x9f, 0x75,
	0x93, 0x2a, 0xf7, 0x10, 0xc6, 0xa5, 0xfb, 0xdf, 0x7c, 0xe1, 0xbc, 0xad, 0x6a, 0xe7, 0xd1, 0x9d,
	0x75, 0x30, 0x2a, 0xd3, 0x0c, 0x8e, 0x4a, 0xd3, 0x7f, 0x23, 0x82, 0x2f, 0xda, 0xda, 0x6b, 0xb3,
	0xea, 0x9e, 0xfc, 0x0f, 0xd5, 0xd4, 0x3b, 0x7b, 0x0b, 0xb3, 0x38, 0xf7, 0x37, 0x82, 0x47, 0x3e,
	0xfd, 0x64, 0x29, 0x4f, 0x48, 0xee, 0x8a, 0xcf, 0x0e, 0x9b, 0x1b, 0x5e, 0x94, 0x9f, 0xca, 0xa2,
	0xb7, 0xbe, 0x6d, 0x7e, 0x97, 0x37, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x9e, 0x32, 0xbc, 0xc8,
	0x6f, 0x04, 0x00, 0x00,
}
